FROM solita/ubuntu-systemd:xenial

RUN apt-get update && apt-get install -y libcurl3-gnutls curl

RUN curl -sL https://deb.nodesource.com/setup_8.x | bash - && \
    apt-get install -y nodejs gcc g++ make
